name: tracks
description: Flutter client for Tracks
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  html: ^0.15.6
  http: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  riverpod_annotation: ^2.3.5
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/stations.json

flutter_launcher_icons:
  android: true
  image_path: assets/icon/icon.png
  adaptive_icon_foreground: assets/icon/adaptive.png
  adaptive_icon_background: '#f13c58'
  adaptive_icon_monochrome: assets/icon/monochrome.png
